### ISSUE TITLE
loop on splore() crashes bot

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/showmepico8#1]
https://twitter.com/0x0ade/status/838233783837020160
```lua
-- @showmepico8
-- i'm sorry
while true do splore() end
```

Much sadness.

**Comment by lemtzas** [comment]
LOL

**Comment by josefnpat** [comment]
If we can't find a way to catch this, I think we can safely `splore=function() end` it

**Comment by 0x0ade** [comment]
This also hangs any actual PICO-8 installation. I once tried to track it using x64dbg and IIRC `splore` maps to a native function in PICO-8.

I assume no tweet would ever try to actually use `splore`, so a (cheap) safety measure would be to `splore=nil`

**Comment by lemtzas** [comment]
i vote for splore = function() print("something funny") end

alternately, anything with "splore" in it could be rejected with a message
